/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CalculatorProject;

public class CalculatorApp {

    
    public static void main(String[] args) {
        CalculatorEngine engine = new CalculatorEngine();
        CalculatorUI ui = new CalculatorUI(engine);
    }
}
